version: '3.8'

services:
  postgres_base:
    container_name: postgres_base
    image: postgres
    restart: always

    ports:
      - 8888:5432

    env_file:
      - ./.env.credenciais
    
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
    driver: local