# Generated by Django 5.1.2 on 2024-10-18 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sabores_pizzas',
            new_name='Sabores',
        ),
    ]
