# Generated by Django 5.1.2 on 2024-10-18 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_rename_sabores_pizzas_sabores'),
    ]

    operations = [
        migrations.AddField(
            model_name='sabores',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 10, 18, 12, 35, 7, 261483)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sabores',
            name='name_sabor',
            field=models.CharField(max_length=30),
        ),
    ]
