# Generated by Django 5.1.2 on 2024-10-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_sabores_created_at_alter_sabores_name_sabor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_cliente', models.CharField(max_length=255)),
                ('cpf_cliente', models.CharField(max_length=14)),
                ('date_aniver', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
