# Generated by Django 5.1.2 on 2024-10-21 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='TamPizzas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_tamanho', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number_mesa', models.CharField(max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fgkey_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.cliente')),
                ('fgkey_sabor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.sabores')),
                ('fgkey_tam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.tampizzas')),
            ],
        ),
    ]
