# Generated by Django 5.1.2 on 2024-10-23 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_tampizzas_pedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterField(
            model_name='pedido',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fgkey_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fgkey_sabor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.sabores', verbose_name='Sabor'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fgkey_tam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.tampizzas', verbose_name='Tamanho'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='number_mesa',
            field=models.IntegerField(max_length=1, verbose_name='Número da Mesa'),
        ),
    ]
