# Generated by Django 5.1.2 on 2024-10-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_alter_pedido_options_alter_pedido_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='number_mesa',
            field=models.IntegerField(verbose_name='Número da Mesa'),
        ),
    ]
